const config = {
  iframe: {
    url1: process.env.NEXT_PUBLIC_PERSONAL_url1,
    url2: process.env.NEXT_PUBLIC_PERSONAL_url2,
    url3: process.env.NEXT_PUBLIC_PERSONAL_url3,
    url4: process.env.NEXT_PUBLIC_PERSONAL_url4,
    url5: process.env.NEXT_PUBLIC_PERSONAL_url5,
    url6: process.env.NEXT_PUBLIC_PERSONAL_url6,
    url7: process.env.NEXT_PUBLIC_PERSONAL_url7,
    url8: process.env.NEXT_PUBLIC_PERSONAL_url8,
    url9: process.env.NEXT_PUBLIC_PERSONAL_url9,
    url10: process.env.NEXT_PUBLIC_PERSONAL_url10,
    url11: process.env.NEXT_PUBLIC_PERSONAL_url11,
    url12: process.env.NEXT_PUBLIC_PERSONAL_url12,
    url13: process.env.NEXT_PUBLIC_PERSONAL_url13,
    url14: process.env.NEXT_PUBLIC_PERSONAL_url14,
    url15: process.env.NEXT_PUBLIC_PERSONAL_url15,
    url16: process.env.NEXT_PUBLIC_PERSONAL_url16,
    url17: process.env.NEXT_PUBLIC_PERSONAL_url17,
    url18: process.env.NEXT_PUBLIC_PERSONAL_url18,
    url19: process.env.NEXT_PUBLIC_PERSONAL_url19,
    url20: process.env.NEXT_PUBLIC_PERSONAL_url20,
    url21: process.env.NEXT_PUBLIC_PERSONAL_url21,
    url22: process.env.NEXT_PUBLIC_PERSONAL_url22,
    url23: process.env.NEXT_PUBLIC_PERSONAL_url23,
    url24: process.env.NEXT_PUBLIC_PERSONAL_url24,
    url25: process.env.NEXT_PUBLIC_PERSONAL_url25,
    urls: [
      process.env.NEXT_PUBLIC_PERSONAL_url25,
      process.env.NEXT_PUBLIC_PERSONAL_url17,
      process.env.NEXT_PUBLIC_PERSONAL_url15,
      process.env.NEXT_PUBLIC_PERSONAL_url1,
      process.env.NEXT_PUBLIC_PERSONAL_url2,
      process.env.NEXT_PUBLIC_PERSONAL_url21,
      process.env.NEXT_PUBLIC_PERSONAL_url22,
      process.env.NEXT_PUBLIC_PERSONAL_url23,
      process.env.NEXT_PUBLIC_PERSONAL_url24,
      process.env.NEXT_PUBLIC_PERSONAL_url8,
      process.env.NEXT_PUBLIC_PERSONAL_url9,
      process.env.NEXT_PUBLIC_PERSONAL_url3,
      process.env.NEXT_PUBLIC_PERSONAL_url4,
      process.env.NEXT_PUBLIC_PERSONAL_url5,
      process.env.NEXT_PUBLIC_PERSONAL_url6,
      process.env.NEXT_PUBLIC_PERSONAL_url20,
      process.env.NEXT_PUBLIC_PERSONAL_url10,
      process.env.NEXT_PUBLIC_PERSONAL_url11,
      process.env.NEXT_PUBLIC_PERSONAL_url16,
      process.env.NEXT_PUBLIC_PERSONAL_url12,
      process.env.NEXT_PUBLIC_PERSONAL_url13,
      process.env.NEXT_PUBLIC_PERSONAL_url14,
      process.env.NEXT_PUBLIC_PERSONAL_url18,
      process.env.NEXT_PUBLIC_PERSONAL_url19,
      process.env.NEXT_PUBLIC_PERSONAL_url7,
    ],
  },
  tmdbApiKey: process.env.NEXT_PUBLIC_PERSONAL_tmdb_api_key,
  latestMediaUrl: process.env.NEXT_PUBLIC_LATEST_MEDIA_url,
  latestMediaUrl1: process.env.NEXT_PUBLIC_LATEST_MEDIA_url1,
};

export default config;
