const config = {
  iframe: {
    url1: process.env.NEXT_PUBLIC_PERSONAL_url1,
    url2: process.env.NEXT_PUBLIC_PERSONAL_url2,
    url3: process.env.NEXT_PUBLIC_PERSONAL_url3,
    url4: process.env.NEXT_PUBLIC_PERSONAL_url4,
    url5: process.env.NEXT_PUBLIC_PERSONAL_url5,
    url6: process.env.NEXT_PUBLIC_PERSONAL_url6,
    url7: process.env.NEXT_PUBLIC_PERSONAL_url7,
    url8: process.env.NEXT_PUBLIC_PERSONAL_url8,
    url9: process.env.NEXT_PUBLIC_PERSONAL_url9,
    url10: process.env.NEXT_PUBLIC_PERSONAL_url10,
    url11: process.env.NEXT_PUBLIC_PERSONAL_url11,
    url12: process.env.NEXT_PUBLIC_PERSONAL_url12,
    url13: process.env.NEXT_PUBLIC_PERSONAL_url13,
    url14: process.env.NEXT_PUBLIC_PERSONAL_url14,
    url15: process.env.NEXT_PUBLIC_PERSONAL_url15,
    urls: [
      process.env.NEXT_PUBLIC_PERSONAL_url7,
      process.env.NEXT_PUBLIC_PERSONAL_url15,
      process.env.NEXT_PUBLIC_PERSONAL_url1,
      process.env.NEXT_PUBLIC_PERSONAL_url2,
      process.env.NEXT_PUBLIC_PERSONAL_url9,
      process.env.NEXT_PUBLIC_PERSONAL_url8,
      process.env.NEXT_PUBLIC_PERSONAL_url3,
      process.env.NEXT_PUBLIC_PERSONAL_url4,
      process.env.NEXT_PUBLIC_PERSONAL_url5,
      process.env.NEXT_PUBLIC_PERSONAL_url6,
      process.env.NEXT_PUBLIC_PERSONAL_url10,
      process.env.NEXT_PUBLIC_PERSONAL_url11,
      process.env.NEXT_PUBLIC_PERSONAL_url12,
      process.env.NEXT_PUBLIC_PERSONAL_url13,
      process.env.NEXT_PUBLIC_PERSONAL_url14,
    ],
  },
  tmdbApiKey: process.env.NEXT_PUBLIC_PERSONAL_tmdb_api_key,
  latestMediaUrl: process.env.NEXT_PUBLIC_LATEST_MEDIA_url,
  latestMediaUrl1: process.env.NEXT_PUBLIC_LATEST_MEDIA_url1,
};

export default config;
