const config = {
  iframe: {
    url1: process.env.NEXT_PUBLIC_PERSONAL_url1,
    url2: process.env.NEXT_PUBLIC_PERSONAL_url2,
    url3: process.env.NEXT_PUBLIC_PERSONAL_url3,
    url4: process.env.NEXT_PUBLIC_PERSONAL_url4,
    url5: process.env.NEXT_PUBLIC_PERSONAL_url5,
    url6: process.env.NEXT_PUBLIC_PERSONAL_url6,
    url7: process.env.NEXT_PUBLIC_PERSONAL_url7,
    url8: process.env.NEXT_PUBLIC_PERSONAL_url8,
    url9: process.env.NEXT_PUBLIC_PERSONAL_url9,
    url10: process.env.NEXT_PUBLIC_PERSONAL_url10,
    url11: process.env.NEXT_PUBLIC_PERSONAL_url11,
    url12: process.env.NEXT_PUBLIC_PERSONAL_url12,
    url13: process.env.NEXT_PUBLIC_PERSONAL_url13,
    url14: process.env.NEXT_PUBLIC_PERSONAL_url14,
    url15: process.env.NEXT_PUBLIC_PERSONAL_url15,
    url16: process.env.NEXT_PUBLIC_PERSONAL_url16,
    url17: process.env.NEXT_PUBLIC_PERSONAL_url17,
    url18: process.env.NEXT_PUBLIC_PERSONAL_url18,
    url19: process.env.NEXT_PUBLIC_PERSONAL_url19,
    url20: process.env.NEXT_PUBLIC_PERSONAL_url20,
    url21: process.env.NEXT_PUBLIC_PERSONAL_url21,
    url23: process.env.NEXT_PUBLIC_PERSONAL_url23,
    url24: process.env.NEXT_PUBLIC_PERSONAL_url24,
    url25: process.env.NEXT_PUBLIC_PERSONAL_url25,
    url26: process.env.NEXT_PUBLIC_PERSONAL_url26,
    url27: process.env.NEXT_PUBLIC_PERSONAL_url27,
    url28: process.env.NEXT_PUBLIC_PERSONAL_url28,
    url29: process.env.NEXT_PUBLIC_PERSONAL_url29,
    url30: process.env.NEXT_PUBLIC_PERSONAL_url30,
    url31: process.env.NEXT_PUBLIC_PERSONAL_url31,
    url32: process.env.NEXT_PUBLIC_PERSONAL_url32,
    url33: process.env.NEXT_PUBLIC_PERSONAL_url33,
    url34: process.env.NEXT_PUBLIC_PERSONAL_url34,
    url35: process.env.NEXT_PUBLIC_PERSONAL_url35,
    url36: process.env.NEXT_PUBLIC_PERSONAL_url36,
    url37: process.env.NEXT_PUBLIC_PERSONAL_url37,
    url38: process.env.NEXT_PUBLIC_PERSONAL_url38,
    url39: process.env.NEXT_PUBLIC_PERSONAL_url39,
    url40: process.env.NEXT_PUBLIC_PERSONAL_url40,
    url41: process.env.NEXT_PUBLIC_PERSONAL_url41,
    url42: process.env.NEXT_PUBLIC_PERSONAL_url42,
    url43: process.env.NEXT_PUBLIC_PERSONAL_url43,
    url44: process.env.NEXT_PUBLIC_PERSONAL_url44,
    url45: process.env.NEXT_PUBLIC_PERSONAL_url45,
    url46: process.env.NEXT_PUBLIC_PERSONAL_url46,
    url47: process.env.NEXT_PUBLIC_PERSONAL_url47,
    url48: process.env.NEXT_PUBLIC_PERSONAL_url48,
    url49: process.env.NEXT_PUBLIC_PERSONAL_url49,
    url50: process.env.NEXT_PUBLIC_PERSONAL_url50,
    url51: process.env.NEXT_PUBLIC_PERSONAL_url51,
    url52: process.env.NEXT_PUBLIC_PERSONAL_url52,
    url53: process.env.NEXT_PUBLIC_PERSONAL_url53,
    url54: process.env.NEXT_PUBLIC_PERSONAL_url54,
    url55: process.env.NEXT_PUBLIC_PERSONAL_url55,
    url56: process.env.NEXT_PUBLIC_PERSONAL_url56,
    url57: process.env.NEXT_PUBLIC_PERSONAL_url57,
    url58: process.env.NEXT_PUBLIC_PERSONAL_url58,
    url59: process.env.NEXT_PUBLIC_PERSONAL_url59,
    url60: process.env.NEXT_PUBLIC_PERSONAL_url60,
    url61: process.env.NEXT_PUBLIC_PERSONAL_url61,
    url62: process.env.NEXT_PUBLIC_PERSONAL_url62,
    url63: process.env.NEXT_PUBLIC_PERSONAL_url63,
    url64: process.env.NEXT_PUBLIC_PERSONAL_url64,
    url65: process.env.NEXT_PUBLIC_PERSONAL_url65,
    url66: process.env.NEXT_PUBLIC_PERSONAL_url66,
    urls: [
      process.env.NEXT_PUBLIC_PERSONAL_url25,
      process.env.NEXT_PUBLIC_PERSONAL_url30,
      process.env.NEXT_PUBLIC_PERSONAL_url27,
      process.env.NEXT_PUBLIC_PERSONAL_url37,
      process.env.NEXT_PUBLIC_PERSONAL_url40,
      process.env.NEXT_PUBLIC_PERSONAL_url45,
      process.env.NEXT_PUBLIC_PERSONAL_url46,
      process.env.NEXT_PUBLIC_PERSONAL_url41,
      process.env.NEXT_PUBLIC_PERSONAL_url43,
      process.env.NEXT_PUBLIC_PERSONAL_url44,
      process.env.NEXT_PUBLIC_PERSONAL_url35,
      process.env.NEXT_PUBLIC_PERSONAL_url36,
      process.env.NEXT_PUBLIC_PERSONAL_url28,
      process.env.NEXT_PUBLIC_PERSONAL_url15,
      process.env.NEXT_PUBLIC_PERSONAL_url2,
      process.env.NEXT_PUBLIC_PERSONAL_url33,
      process.env.NEXT_PUBLIC_PERSONAL_url21,
      process.env.NEXT_PUBLIC_PERSONAL_url29,
      process.env.NEXT_PUBLIC_PERSONAL_url8,
      process.env.NEXT_PUBLIC_PERSONAL_url32,
      process.env.NEXT_PUBLIC_PERSONAL_url3,
      process.env.NEXT_PUBLIC_PERSONAL_url4,
      process.env.NEXT_PUBLIC_PERSONAL_url10,
      process.env.NEXT_PUBLIC_PERSONAL_url13,
      process.env.NEXT_PUBLIC_PERSONAL_url50,
      process.env.NEXT_PUBLIC_PERSONAL_url51,
      process.env.NEXT_PUBLIC_PERSONAL_url53,
      process.env.NEXT_PUBLIC_PERSONAL_url57,
      process.env.NEXT_PUBLIC_PERSONAL_url58,
      process.env.NEXT_PUBLIC_PERSONAL_url59,
      process.env.NEXT_PUBLIC_PERSONAL_url60,
      process.env.NEXT_PUBLIC_PERSONAL_url61,
      process.env.NEXT_PUBLIC_PERSONAL_url62,
      process.env.NEXT_PUBLIC_PERSONAL_url63,
      process.env.NEXT_PUBLIC_PERSONAL_url64,
      process.env.NEXT_PUBLIC_PERSONAL_url65,
      process.env.NEXT_PUBLIC_PERSONAL_tab_url2,
      process.env.NEXT_PUBLIC_PERSONAL_url34,
      process.env.NEXT_PUBLIC_PERSONAL_url38,
      process.env.NEXT_PUBLIC_PERSONAL_url42,
      process.env.NEXT_PUBLIC_PERSONAL_url17,
      process.env.NEXT_PUBLIC_PERSONAL_tab_url3,
      process.env.NEXT_PUBLIC_PERSONAL_url24,
      process.env.NEXT_PUBLIC_PERSONAL_url9,
      process.env.NEXT_PUBLIC_PERSONAL_url5,
      process.env.NEXT_PUBLIC_PERSONAL_url6,
      process.env.NEXT_PUBLIC_PERSONAL_url20,
      process.env.NEXT_PUBLIC_PERSONAL_url11,
      process.env.NEXT_PUBLIC_PERSONAL_url16,
      process.env.NEXT_PUBLIC_PERSONAL_url12,
      process.env.NEXT_PUBLIC_PERSONAL_url14,
      process.env.NEXT_PUBLIC_PERSONAL_url18,
      process.env.NEXT_PUBLIC_PERSONAL_url19,
      process.env.NEXT_PUBLIC_PERSONAL_url23,
      process.env.NEXT_PUBLIC_PERSONAL_url7,
      process.env.NEXT_PUBLIC_PERSONAL_url26,
      process.env.NEXT_PUBLIC_PERSONAL_url1,
      process.env.NEXT_PUBLIC_PERSONAL_url39,
      process.env.NEXT_PUBLIC_PERSONAL_url31,
      process.env.NEXT_PUBLIC_PERSONAL_url47,
      process.env.NEXT_PUBLIC_PERSONAL_url48,
      process.env.NEXT_PUBLIC_PERSONAL_url49,
      process.env.NEXT_PUBLIC_PERSONAL_url52,
      process.env.NEXT_PUBLIC_PERSONAL_url54,
      process.env.NEXT_PUBLIC_PERSONAL_url55,
      process.env.NEXT_PUBLIC_PERSONAL_url56,
      process.env.NEXT_PUBLIC_PERSONAL_url66,
      process.env.NEXT_PUBLIC_PERSONAL_tab_url1,
    ].filter(Boolean),
    animeUrls: [
      process.env.NEXT_PUBLIC_PERSONAL_url25,
      process.env.NEXT_PUBLIC_PERSONAL_url50,
      process.env.NEXT_PUBLIC_PERSONAL_url16,
      process.env.NEXT_PUBLIC_PERSONAL_url66,
      process.env.NEXT_PUBLIC_PERSONAL_url59,
      process.env.NEXT_PUBLIC_PERSONAL_url40,
      process.env.NEXT_PUBLIC_PERSONAL_url41,
      process.env.NEXT_PUBLIC_PERSONAL_url42,
      process.env.NEXT_PUBLIC_PERSONAL_url43,
      process.env.NEXT_PUBLIC_PERSONAL_url44,
    ].filter(Boolean)
  },
  tabs:[
      process.env.NEXT_PUBLIC_PERSONAL_tab_url1,
      process.env.NEXT_PUBLIC_PERSONAL_tab_url2,
      process.env.NEXT_PUBLIC_PERSONAL_tab_url3,
  ],
  tmdbApiKey: process.env.NEXT_PUBLIC_PERSONAL_tmdb_api_key,
  latestMediaUrl: process.env.NEXT_PUBLIC_LATEST_MEDIA_url,
  latestMediaUrl1: process.env.NEXT_PUBLIC_LATEST_MEDIA_url1,
};

config.iframe.nonAnimeUrls = config.iframe.urls.filter(
  (url) =>
    ![
      config.iframe.url40,
      config.iframe.url41,
      config.iframe.url43,
      config.iframe.url66,
    ].includes(url),
);

export const getIframeSourceName = (sourceUrl) => {
  const source = Object.entries(config.iframe).find(
    ([key, value]) => /^url\d+$/.test(key) && value === sourceUrl,
  );

  if (source) return `URL ${source[0].replace("url", "")}`;

  const tabIndex = config.tabs.filter(Boolean).indexOf(sourceUrl);
  if (tabIndex >= 0) return `Tab URL ${tabIndex + 1}`;

  return "Unknown URL";
};

export default config;
