/**
 * Tests configured iframe sources with a real media query generated by
 * src/helper/iframeFunc.js.
 *
 * Change `query` to test another movie, TV episode, or anime episode.
 * Usage: node scripts/checkUrls.mjs
 */

import fs from "fs";
import { registerHooks } from "node:module";
import path from "path";
import { fileURLToPath, pathToFileURL } from "url";

process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

const query = process.argv[2] || "0-tv-220102-1-1";
const TIMEOUT_MS = 8000;
const RELATIVE_URL_ORIGIN = "http://localhost:3000";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const SRC_ROOT = path.join(ROOT, "src");
const SRC_ROOT_URL = `${pathToFileURL(SRC_ROOT).href}/`;

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};

  const env = {};
  for (const line of fs.readFileSync(filePath, "utf8").split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;

    const separatorIndex = trimmed.indexOf("=");
    if (separatorIndex === -1) continue;

    const key = trimmed.slice(0, separatorIndex).trim();
    let value = trimmed.slice(separatorIndex + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    env[key] = value;
  }

  return env;
}

const env = parseEnvFile(path.join(ROOT, ".env.local"));
Object.assign(process.env, env);

// Node does not understand the Next.js `@/` alias or ESM app files by default.
// These hooks let this script execute the real config and iframe helper.
registerHooks({
  load(url, context, nextLoad) {
    if (url.startsWith(SRC_ROOT_URL) && url.endsWith(".js")) {
      return {
        format: "module",
        shortCircuit: true,
        source: fs.readFileSync(fileURLToPath(url), "utf8"),
      };
    }
    return nextLoad(url, context);
  },
  resolve(specifier, context, nextResolve) {
    if (!specifier.startsWith("@/")) {
      return nextResolve(specifier, context);
    }

    let resolvedPath = path.join(SRC_ROOT, specifier.slice(2));
    if (!path.extname(resolvedPath)) {
      if (fs.existsSync(`${resolvedPath}.js`)) {
        resolvedPath = `${resolvedPath}.js`;
      } else {
        resolvedPath = path.join(resolvedPath, "index.js");
      }
    }

    return {
      shortCircuit: true,
      url: pathToFileURL(resolvedPath).href,
    };
  },
});

const [{ default: config, getIframeSourceName }, iframeHelpers] =
  await Promise.all([
    import(pathToFileURL(path.join(SRC_ROOT, "config/index.js")).href),
    import(pathToFileURL(path.join(SRC_ROOT, "helper/iframeFunc.js")).href),
  ]);
const { getIframeObjectFromUrl, getIframeUrl } = iframeHelpers;

const queryParts = query.split("-");
if (queryParts.length < 3) {
  throw new Error(
    `Invalid query "${query}". Expected: sourceIndex-type-id-season-episode`,
  );
}

const [, type, ...mediaParts] = queryParts;
const sourceUrls =
  type === "anime"
    ? config.iframe.animeUrls
    : config.iframe.nonAnimeUrls || config.iframe.urls;

function findEnvKey(baseUrl) {
  return Object.keys(env).find(
    (key) =>
      /^NEXT_PUBLIC_PERSONAL_(?:url\d+|tab_url\d+)$/.test(key) &&
      env[key] === baseUrl,
  );
}

const urlEntries = sourceUrls.map((baseUrl) => {
  const sourceIndex = config.iframe.urls.indexOf(baseUrl);
  const sourceQuery = [sourceIndex, type, ...mediaParts].join("-");
  const iframeUrl = getIframeObjectFromUrl({ url: `?url=${sourceQuery}` });

  if (!iframeUrl) {
    throw new Error(`Could not parse source query: ${sourceQuery}`);
  }

  const generatedUrl = getIframeUrl({ iframeUrl: { ...iframeUrl } });
  return {
    baseUrl,
    envKey: findEnvKey(baseUrl),
    generatedUrl: new URL(generatedUrl, RELATIVE_URL_ORIGIN).href,
    name: getIframeSourceName(baseUrl),
    sourceIndex,
    sourceQuery,
  };
});

if (urlEntries.length === 0) {
  throw new Error("No configured iframe URLs found in .env.local.");
}

console.log(`Query: ?url=${query}`);
console.log(`Testing ${urlEntries.length} ${type} sources...\n`);

async function testUrl(url) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);
  const start = Date.now();

  try {
    const response = await fetch(url, {
      headers: {
        Accept: "text/html,application/xhtml+xml",
        "User-Agent":
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/138 Safari/537.36",
      },
      redirect: "follow",
      signal: controller.signal,
    });
    const elapsed = Date.now() - start;
    const blocked = [401, 403, 429].includes(response.status);

    return {
      elapsed,
      state: response.ok ? "working" : blocked ? "blocked" : "broken",
      status: response.status,
    };
  } catch (error) {
    return {
      elapsed: Date.now() - start,
      state: "broken",
      status: error.name === "AbortError" ? "TIMEOUT" : "ERROR",
    };
  } finally {
    clearTimeout(timer);
  }
}

const results = await Promise.all(
  urlEntries.map(async (entry) => {
    const result = await testUrl(entry.generatedUrl);
    const icon =
      result.state === "working" ? "✓" : result.state === "blocked" ? "?" : "✗";

    console.log(
      `${icon} [${String(result.status).padStart(7)}] ${String(result.elapsed).padStart(5)}ms  ${entry.name.padEnd(10)} index=${String(entry.sourceIndex).padEnd(2)} ${entry.generatedUrl}`,
    );
    return { ...entry, ...result };
  }),
);

const working = results
  .filter((result) => result.state === "working")
  .sort((a, b) => a.elapsed - b.elapsed);
const blocked = results.filter((result) => result.state === "blocked");
const broken = results.filter((result) => result.state === "broken");

console.log("\n--- Results ---");
console.log(
  `Working: ${working.length} | Bot-blocked: ${blocked.length} | Broken/timeout: ${broken.length}`,
);

if (blocked.length) {
  console.log("\nBot-blocked; verify these in a browser:");
  blocked.forEach((result) =>
    console.log(`  ${result.name} [${result.status}] ?url=${result.sourceQuery}`),
  );
}

if (broken.length) {
  console.log("\nBroken URLs:");
  broken.forEach((result) =>
    console.log(`  ${result.name} [${result.status}] ?url=${result.sourceQuery}`),
  );
}

console.log("\nWorking sources, fastest first:");
working.forEach((result) =>
  console.log(
    `  ${result.envKey ? `process.env.${result.envKey}` : result.name}, // ${result.elapsed}ms`,
  ),
);
